# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor

random_1 = torch.rand(7, 7)
random_1


tensor([[0.3197, 0.4127, 0.0809, 0.4110, 0.0554, 0.6140, 0.2543],
        [0.5967, 0.8848, 0.6095, 0.8866, 0.0819, 0.0554, 0.2224],
        [0.5003, 0.4242, 0.0201, 0.3470, 0.4830, 0.9296, 0.4951],
        [0.4639, 0.7532, 0.4940, 0.8545, 0.7642, 0.1003, 0.7456],
        [0.6830, 0.2727, 0.6351, 0.6969, 0.2122, 0.4631, 0.0177],
        [0.4194, 0.1111, 0.2076, 0.7642, 0.3076, 0.1074, 0.3915],
        [0.6397, 0.3590, 0.5075, 0.5918, 0.9006, 0.9827, 0.9447]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_2 = torch.rand(1, 7)
# Perform matrix multiplication
random_1.mm(random_2.T)


tensor([[1.3344],
        [2.6261],
        [1.9386],
        [3.1153],
        [2.3013],
        [1.8119],
        [3.2770]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)


# Create two random tensors
random_3 = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
random_4 = torch.rand(1, 7)

matrix = random_3.mm(random_4.T)

matrix, matrix.shape


# Matrix multiply tensors


(tensor([[3.2618],
         [3.4084],
         [2.4866],
         [1.4525],
         [1.7079],
         [2.7291],
         [2.9204]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.cuda.manual_seed(1234)


# Check for access to GPU
Device = "cuda" if torch.cuda.is_available() else "cpu"
Device
# Create two random tensors on GPU
tensor_1 = torch.rand(size=(2, 3), device=Device)
tensor_2 = torch.rand(size=(2,3), device=Device)
tensor_1,tensor_2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
tensor_matrix = tensor_1.mm(tensor_2.T)
tensor_matrix


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [26]:
# Find max
torch.max(tensor_matrix)

# Find min
torch.min(tensor_matrix)


tensor(0.2786, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
torch.argmax(tensor_matrix)


# Find arg min
torch.argmin(tensor_matrix)


tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [30]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1,1,1,10)


# Remove single dimensions
random_tensor.squeeze().shape


# Print out tensors and their shapes


torch.Size([10])