In [1]:
!nvidia-smi

Mon May 13 16:16:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 00. Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4,6,7],[8, 9, 10]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  6,  7],
         [ 8,  9, 10]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  6,  7],
        [ 8,  9, 10]])

In [17]:
TENSOR[0][0]

tensor([1, 2, 3])

In [18]:
RANDOM = torch.tensor([[[[1,2,3],[4,6,7],[8,8,8]]]])
RANDOM

tensor([[[[1, 2, 3],
          [4, 6, 7],
          [8, 8, 8]]]])

In [19]:
RANDOM.ndim

4

In [20]:
RANDOM.shape

torch.Size([1, 1, 3, 3])

### Random tensors

why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update a random numbers`

In [21]:
# Create a random tensors of size/shape (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8119, 0.8314, 0.0768, 0.7712],
        [0.7340, 0.7319, 0.8954, 0.6788],
        [0.2832, 0.1698, 0.4905, 0.2819]])

In [22]:
random_tensor.ndim

2

In [23]:
# Create a randomm tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,244,3)) # height, width, colour channels(R,G,B)
random_image_size_tensor

tensor([[[0.9936, 0.2003, 0.6979],
         [0.1749, 0.5050, 0.0772],
         [0.2217, 0.0507, 0.3112],
         ...,
         [0.5798, 0.7673, 0.7521],
         [0.7161, 0.6327, 0.7009],
         [0.9000, 0.7161, 0.2357]],

        [[0.3194, 0.2503, 0.7034],
         [0.2766, 0.8592, 0.6258],
         [0.3052, 0.8998, 0.2190],
         ...,
         [0.8962, 0.8064, 0.6452],
         [0.3489, 0.5660, 0.5702],
         [0.6383, 0.6179, 0.1604]],

        [[0.3306, 0.6678, 0.8535],
         [0.7251, 0.2005, 0.6379],
         [0.1820, 0.1713, 0.5269],
         ...,
         [0.8676, 0.0552, 0.4131],
         [0.5857, 0.6195, 0.9293],
         [0.9331, 0.9611, 0.1804]],

        ...,

        [[0.7296, 0.3776, 0.9348],
         [0.1752, 0.0757, 0.7688],
         [0.2793, 0.3422, 0.1099],
         ...,
         [0.1239, 0.3313, 0.3349],
         [0.6937, 0.0334, 0.1497],
         [0.5758, 0.5965, 0.2814]],

        [[0.1638, 0.4678, 0.8047],
         [0.0541, 0.1711, 0.7846],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 244, 3])

### Zeros and ones

In [26]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-line

In [30]:
range_tensor = torch.arange(start=1, end=11, step=1)
range_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=range_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
 **Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
 1. Tensors not right datatypes
 2. Tensors not right shape
 3. Tensors not on the right device

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor (e.g float32, float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor oparation
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. Tensors not right datatypes - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [38]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5260, 0.6953, 0.4024, 0.1149],
        [0.9211, 0.0692, 0.0681, 0.3837],
        [0.9293, 0.0374, 0.2954, 0.4667]])

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.5260, 0.6953, 0.4024, 0.1149],
        [0.9211, 0.0692, 0.0681, 0.3837],
        [0.9293, 0.0374, 0.2954, 0.4667]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor opertions includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [40]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [42]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [43]:
# in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix mulptiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)


THere are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimesions** must match:
    * `(3, 2) @ (3, 2)` won't work
    * `(2, 3) @ (3, 2)` will work
    * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
    * `(2, 3) @ (3, 2)` -> `(2, 2)`
    * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [45]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [46]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [47]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [48]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [49]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.15 ms, sys: 949 µs, total: 2.1 ms
Wall time: 3.16 ms


In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 6 µs, total: 39 µs
Wall time: 42.2 µs


tensor(14)

### One of the most common erros in deep learning is Shape Error

In [52]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],[3, 4],[5, 6]])

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **Transpose**

a **transpose** switches the axes or dimesions of a given tensor

In [53]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [54]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [55]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [56]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [57]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [59]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [60]:
# Find the mean
# Note the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [61]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [62]:
# Positional Min and Max (which position the highest and lowest are at)
torch.argmax(x), torch.argmin(x)

(tensor(9), tensor(0))

In [63]:
x[9], x[0]

(tensor(90), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but  keep the same memory
  as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or  side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimesions permuted (swapped) in a certain way

In [64]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
# Add an extran dimension
x_reshaped = x.reshape(1, 9)
x_reshaped.shape, x_reshaped

(torch.Size([1, 9]), tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [66]:
# Change the view
z = x.view(1, 9)

z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# Changing z changes x (because a view of a tensor shares the same memoru as the original)
z[:, 0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [68]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [69]:
x_vstacked = torch.vstack([x,x,x,x])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [70]:
x_hstack = torch.hstack([x, x, x,x])
x_hstack

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [71]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [72]:
x_reshaped.shape

torch.Size([1, 9])

In [73]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [74]:
x_reshaped.squeeze().shape

torch.Size([9])

In [75]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [76]:
# torch.unsqueeze() - adds  single dimensions to a target tensor
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimensions to x_squeeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [77]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0-> 1, 1-> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shpae: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shpae: torch.Size([3, 224, 224])


In [78]:
x_original[0,0,0] = 1

In [79]:
x_permuted[0,0,0]

tensor(1.)

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [80]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [81]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [82]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [83]:
x[0, 2, 2]

tensor(9)

In [84]:
# use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [85]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [86]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1, 1]

tensor([5])

In [87]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [88]:
x[:,2,2]

tensor([9])

In [89]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [90]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch reflects numpy's default datatype of float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [93]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
numpy_tensor.dtype

dtype('float32')

In [95]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Peproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again...`


To reduce the randomness in neural networks abd PyTorch comes the concepts of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [96]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7446, 0.0055, 0.7810, 0.6702],
        [0.9701, 0.1043, 0.9177, 0.5869],
        [0.6081, 0.9302, 0.1590, 0.4303]])
tensor([[0.7723, 0.7568, 0.7527, 0.6513],
        [0.1322, 0.6346, 0.7226, 0.0341],
        [0.5057, 0.7545, 0.7883, 0.9962]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
# reproducible tensors
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)


In [98]:
torch.cuda.is_available()

True

In [99]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [100]:
# Count number of devices
torch.cuda.device_count()

1

In [101]:
tensor = torch.tensor([1, 2, 3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [102]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [104]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [105]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

###  Exercises